function validateUserInfo(){$.ajax({url:'/buy/user-info/',method:'post',data:$('#buyform').serialize(),dataType:"json",success:function(data){$('.error').removeClass('error');$('.form__error').html('').hide();if($('#gAutocomplete').val()==''||$('#lat').val()==''||$('#lng').val()==''||$('#country').val()==''){$('.location_box .select2-container').addClass('error');}
if(data.status=='success'){toStep2();}else{firstError=null;$.each(data.errors,function(key,value){er=[];$.each(value,function(k,v){er.push(v);});$('#buyform').find('#'+key).addClass('error');$('#buyform').find('#'+key).parent().find('.form__error').html(er.join('; ')).show();if(firstError==null){firstError=$('#buyform').find('#'+key).parent();}});if(firstError==null){firstError=$('#buyform');}
$('html, body').animate({scrollTop:(firstError.offset().top-100)},500);}}});}
function validateUserInfoFree(){$.ajax({url:'/test/user-info/',method:'post',data:$('#buyform').serialize(),dataType:"json",success:function(data){$('.error').removeClass('error');$('.form__error').html('');if($('#gAutocomplete').value==''||$('#lat').value==''||$('#lng').value==''||$('#country').value==''){$('#gAutocomplete').addClass('error');}
if(data.status=='success'){toFree();}else{firstError=null;$.each(data.errors,function(key,value){er=[];$.each(value,function(k,v){er.push(v);});$('#buyform').find('#'+key).addClass('error');$('#buyform').find('#'+key).closest('.field_box').find('.form__error').html(er.join('; ')).show();if(firstError==null){firstError=$('#buyform').find('#'+key).closest('.field_box');}});if(firstError==null){firstError=$('#buyform');}
$('html, body').animate({scrollTop:(firstError.offset().top-100)},500);}}});}
function toFree(){$('#step1 .step-content').hide();$('#step2 .step-content').show();$.ajax({url:'/test/free/',success:function(data){$('#step2 .step-content').html(data);$('.box-hide .box-title').on('click',function(){$(this).closest('.box-hide').find('.box-content').slideToggle();$(this).toggleClass('open');});}});}
function toStep2(){$.ajax({url:'/buy/pay-method/',success:function(data){$('#step2 .step-content').html(data);showStep2();initEvent();}});}
function initEvent(){document.body.scrollTop=document.documentElement.scrollTop=0;$('.order__change').on('click',function(){showStep1();return false;});$('.order__list-payment .payment').on('click',function(){$('.order__list-payment .payment').removeClass('active');$(this).addClass('active');var select=$(this).data('select');$('#'+select).prop('checked','checked');$('#toStep3').click();});$('#toStep3').on('click',function(){$.ajax({url:'/buy/pay/',method:'post',data:$('#payform').serialize(),success:function(data){$('#step3 .step-content').html(data);showStep3();initEvent();}});});$('form.form-code').submit(function(){if($(this).find('input').val().length>3){return true;}
return false;});$('.addition-product .data__item').on('click',function(){$(this).toggleClass('active');var func='add';if($(this).hasClass('active')){$(this).find('.btn-ico').html('-');$(this).closest('li').find('.about_block').slideDown();}else{$(this).find('.btn-ico').html('+');func='rem';$(this).closest('li').find('.about_block').slideUp();}
$.ajax({url:'/buy/addition-product/',method:'post',data:{id:$(this).data('id'),func:func},dataType:"json",success:function(data){$('.addition-product .total-price').html(data.price);}});});}
function showStep1(){$('#tab1').removeClass('not-active').addClass('active');$('#tab2').removeClass('active').addClass('not-active');$('#tab3').removeClass('active').addClass('not-active');$('#step2 .step-content').hide();$('#step3 .step-content').hide();$('#step1 .step-content').show();}
function showStep2(){$('#tab1').removeClass('not-active').addClass('active');$('#tab2').removeClass('not-active').addClass('active');$('#step1 .step-content').hide();$('#step3 .step-content').hide();$('#step2 .step-content').show();}
function showStep3(){$('#tab1').removeClass('not-active').addClass('active');$('#tab2').removeClass('not-active').addClass('active');$('#step1 .step-content').hide();$('#step2 .step-content').hide();$('#step3 .step-content').show();}
$('document').ready(function(){if($('#gAutocomplete').value!=''&&$('#lat').value!=''&&$('#lng').value!=''&&$('#country').value!=''){$('#toStep2').prop('disabled',false);}
$('#toStep2').on('click',function(){validateUserInfo();return true;});$('#toFree').on('click',function(){validateUserInfoFree();return true;});$('.mask-time').inputmask('h:s',{alias:"datetime",hourFormat:'24'});if($('#autocomplete').val()!=''){$(".js-select--loc").data('placeholder',$('#autocomplete').val());}
if($('#defStep').val()=='2'){$('#toStep2').trigger('click');}
$(".js-select--loc").select2({ajax:{delay:500,url:'/ajax/location/',dataType:'json',data:function(params){var aida=$('#ak').val();var query={aida:aida,q:params.term,};return query;}},width:"100%",minimumInputLength:3,language:'ru',}).on("select2:open",function(e){event.preventDefault();$('.select2-search__field').trigger('focus');if($(".js-select--loc").parent().find('.form__error').length){$(".js-select--loc").parent().find('.form__error').html('').hide();}}).on('select2:select',function(e){var data=e.params.data;$('.js-select--loc').removeClass('error');$('#lat').val('');$('#lng').val('');$('#locality').val('');$('#administrative').val('');$('#country').val('');$('#autocomplete').val(data.text);$.ajax({url:'/ajax/locationselect/',method:'post',data:'id='+data.id,success:function(data){if(data.status=='OK'){$('#lat').val(data.lat);$('#lng').val(data.lng);$('#locality').val(data.locality);$('#administrative').val(data.administrative);$('#country').val(data.country);}else{$('.js-select--loc').addClass('error');}}});});if($('#PartnerAutocomplete').val()!=''){$(".js-select--loc-parent").data('placeholder',$('#PartnerAutocomplete').val());}
$(".js-select--loc-parent").select2({ajax:{delay:500,url:'/ajax/location/',dataType:'json',data:function(params){var aida=$('#ak').val();var query={aida:aida,q:params.term,};return query;}},width:"100%",minimumInputLength:3,language:'ru',}).on("select2:open",function(e){event.preventDefault();$('.select2-search__field').trigger('focus');if($(".js-select--loc-parent").parent().find('.form__error').length){$(".js-select--loc-parent").parent().find('.form__error').html('').hide();}}).on('select2:select',function(e){var data=e.params.data;$('.js-select--loc-parent').removeClass('error');$('#PartnerLat').val('');$('#PartnerLng').val('');$('#PartnerLocality').val('');$('#PartnerAdministrative').val('');$('#PartnerCountry').val('');$('#PartnerAutocomplete').val(data.text);$.ajax({url:'/ajax/locationselect/',method:'post',data:'id='+data.id,success:function(data){if(data.status=='OK'){$('#PartnerLat').val(data.lat);$('#PartnerLng').val(data.lng);$('#PartnerLocality').val(data.locality);$('#PartnerAdministrative').val(data.administrative);$('#PartnerCountry').val(data.country);}else{$('.js-select--loc-parent').addClass('error');}}});});});