function validateUserInfoBase(form,url,callback){$.ajax({url:url,method:'post',data:form.serialize(),dataType:"json",success:function(data){form.find('.error').removeClass('error');form.find('.form__error').html('').hide();if(form.find('#gAutocomplete').val()==''||form.find('#lat').val()==''||form.find('#lng').val()==''||form.find('#country').val()==''){form.find('.location_box .select2-container').addClass('error');}
if(typeof data.username!=='undefined'){form.find('.username').html(data.username);}
if(typeof data.sign!=='undefined'){form.find('.sign_name').html(data.sign.name);form.find('.sign_text').html(data.sign.text);form.find('.sign_img').attr('src',data.sign.img);if(typeof data.sign.namePartner!=='undefined'){form.find('.sign_p_name').html(data.sign.namePartner);}
if(typeof data.sign.imgPartner!=='undefined'){form.find('.sign_p_img').attr('src',data.sign.imgPartner);}}
if(data.status=='success'){callback();}else{firstError=null;$.each(data.errors,function(key,value){er=[];$.each(value,function(k,v){er.push(v);});form.find('#'+key).addClass('error');form.find('#'+key).closest('.field_box').find('.form__error').html(er.join('; ')).show();if(firstError==null){firstError=form.find('#'+key).closest('.field_box');}});if(firstError==null){firstError=form;}
if(typeof firstError!=='undefined'&&firstError.length){console.log(firstError);$('html, body').animate({scrollTop:(firstError.offset().top-100)},500);}}}});}
function toFreeHome(){window.location.href='/free/report/';}
function toBuy(){window.location.href='/buy?step=2';}
function initAutocomplete(form){if(form.find('#autocomplete').val()!=''){form.find(".js-select--loc").data('placeholder',form.find('#autocomplete').val());}
form.find(".js-select--loc").select2({ajax:{delay:750,url:'/ajax/location/',dataType:'json',data:function(params){var aida=$('#ak').val();var query={aida:aida,q:params.term,};return query;}},width:"100%",minimumInputLength:3,language:'ru',}).on("select2:open",function(e){event.preventDefault();$('.select2-search__field').trigger('focus');if(form.find(".js-select--loc").parent().find('.form__error').length){form.find(".js-select--loc").parent().find('.form__error').html('').hide();}}).on('select2:select',function(e){var data=e.params.data;form.find('.js-select--loc').removeClass('error');form.find('#lat').val('');form.find('#lng').val('');form.find('#locality').val('');form.find('#administrative').val('');form.find('#country').val('');form.find('#autocomplete').val(data.text);$.ajax({url:'/ajax/locationselect/',method:'post',data:'id='+data.id,success:function(data){if(data.status=='OK'){form.find('#lat').val(data.lat);form.find('#lng').val(data.lng);form.find('#locality').val(data.locality);form.find('#administrative').val(data.administrative);form.find('#country').val(data.country);}else{form.find('.js-select--loc').addClass('error');}}});});if($('#PartnerAutocomplete').length>0){if($('#PartnerAutocomplete').val()!=''){$(".js-select--loc-parent").data('placeholder',$('#PartnerAutocomplete').val());}
$(".js-select--loc-parent").select2({ajax:{delay:500,url:'/ajax/location/',dataType:'json',data:function(params){var aida=$('#ak').val();var query={aida:aida,q:params.term,};return query;}},width:"100%",minimumInputLength:3,language:'ru',}).on("select2:open",function(e){event.preventDefault();$('.select2-search__field').trigger('focus');if(form.find(".js-select--loc-parent").parent().find('.form__error').length){form.find(".js-select--loc-parent").parent().find('.form__error').html('').hide();}}).on('select2:select',function(e){var data=e.params.data;$('.js-select--loc-parent').removeClass('error');$('#PartnerLat').val('');$('#PartnerLng').val('');$('#PartnerLocality').val('');$('#PartnerAdministrative').val('');$('#PartnerCountry').val('');$('#PartnerAutocomplete').val(data.text);$.ajax({url:'/ajax/locationselect/',method:'post',data:'id='+data.id,success:function(data){if(data.status=='OK'){$('#PartnerLat').val(data.lat);$('#PartnerLng').val(data.lng);$('#PartnerLocality').val(data.locality);$('#PartnerAdministrative').val(data.administrative);$('#PartnerCountry').val(data.country);}else{$('.js-select--loc-parent').addClass('error');}}});});}}
function initFree(){var mainForm=$('#freeform');$('#toFree').on('click',function(){validateUserInfoBase(mainForm,'/free/user-info/',toFreeHome);return true;});mainForm.find('.mask-time').inputmask('h:s',{alias:"datetime",hourFormat:'24'});initAutocomplete(mainForm);}
function initFree2(){var mainForm=$('#freeform2');$('#toFree2').on('click',function(){validateUserInfoBase(mainForm,'/buy/user-info/',toFreeHome);return true;});mainForm.find('.mask-time').inputmask('h:s',{alias:"datetime",hourFormat:'24'});initAutocomplete(mainForm);}
function initBuyHome(){var mainForm=$('#buyhome');$('#toBuy').on('click',function(){validateUserInfoBase(mainForm,'/buy/user-info/',toBuy);return true;});mainForm.find('.mask-time').inputmask('h:s',{alias:"datetime",hourFormat:'24'});initAutocomplete(mainForm);}
function initFreeNew(){var mainForm=$('#freeformnew');$('#toFreeNew').on('click',function(){validateUserInfoBase(mainForm,'/buy/user-info/',function(){window.location.href='/free/email/';});return true;});mainForm.find('.mask-time').inputmask('h:s',{alias:"datetime",hourFormat:'24'});initAutocomplete(mainForm);}
function initCabinet(){var mainForm=$('#cabinetForm');mainForm.find('#calculate').on('click',function(){validateUserInfoBase(mainForm,'/cabinet/user-info/',function(){mainForm.submit();});return true;});mainForm.find('.mask-time').inputmask('h:s',{alias:"datetime",hourFormat:'24'});initAutocomplete(mainForm);}
function setNewStep(step){$('.interview').removeClass('step1').removeClass('step2').removeClass('step2-1').removeClass('step3').removeClass('step4').removeClass('step4-1');$('.interview').addClass('step'+step);$('#Step').val(step);}
function initNewFree(){var mainForm=$('#new_freeform');mainForm.find('.prev-link').on('click',function(){var step=$(this).data('step');setNewStep(step);return false;});mainForm.find('.to_next').on('click',function(){var step=$(this).data('step');var stepvalid=$(this).data('stepvalid');mainForm.find('#Step').val(step);if(typeof stepvalid!=='undefined'){mainForm.find('#StepValid').val(stepvalid);}else{mainForm.find('#StepValid').val(step);}
if(step=='5'){validateUserInfoBase(mainForm,'/free/user-info/',toFreeHome);}else{validateUserInfoBase(mainForm,'/free/user-info/',function(){setNewStep(step);});}});initAutocomplete(mainForm);mainForm.find('.mask-time').inputmask('h:s',{alias:"datetime",hourFormat:'24'});$('.interview__logo .fico-arrowBtn').on('click',function(){var step=mainForm.find('#Step').val();if(step=='2'){setNewStep('1');}
if(step=='2-1'){setNewStep('2');}
if(step=='3'){setNewStep('2');}
if(step=='4'){setNewStep('3');}
if(step=='4-1'){setNewStep('4');}});$('#timeHelp').on('click',function(){if($(this).prop('checked')){$('#Time').prop('disabled',true);$('#PartnerTime').prop('disabled',true);$('.timeHelper').show();}else{$('#Time').prop('disabled',false);$('#PartnerTime').prop('disabled',false);$('.timeHelper').hide();}});}
function initLoveForm(mainForm){mainForm.find('.mask-date').on('keyup',function(){if($(this).val().replace(/_/g,'').length>=6){var box=$(this).closest('.box');$.ajax({url:'/ajax/sign/',method:'post',data:{date:$(this).val()},dataType:"json",success:function(data){if(data.status=='success'){box.find('.img_box img').attr('src',data.sign.img);}}});}});mainForm.find('#toLove').on('click',function(){if(mainForm.find('#DateFirst').val().replace(/_/g,'').length==10&&mainForm.find('#DateSecond').val().replace(/_/g,'').length==10){mainForm.submit();}
return true;});}
$('document').ready(function(){$('.mask-date').inputmask('d.m.y',{alias:"date",});if($('#freeform').length){initFree();}
if($('#freeform2').length){initFree2();}
if($('#buyhome').length){initBuyHome();}
if($('#freeformnew').length){initFreeNew();}
if($('#new_freeform').length){initNewFree();}
if($('#loveform').length){initLoveForm($('#loveform'));}
if($('#loveform2').length){initLoveForm($('#loveform2'));}
if($('#cabinetForm').length){initCabinet();}
$('.box-hide .box-title').on('click',function(){$(this).closest('.box-hide').find('.box-content').slideToggle();$(this).toggleClass('open');});$('input').on('keyup',function(){$(this).removeClass('error');if($(this).closest('.field_box').find('.form__error').length){$(this).closest('.field_box').find('.form__error').html('').hide();}});$('select').on('change',function(){$(this).removeClass('error');if($(this).closest('.field_box').find('.form__error').length){$(this).closest('.field_box').find('.form__error').html('').hide();}});});